### ISSUE TITLE
Foundation for local development

### ISSUE THREAD

**Issue by akranga** [epam/llmops-hub#5]
Create foundation stack for local development. Today we do not always need or want to run application development in the cloud. Such stack can be use as the basis for `on-prem` deployment because presence of Kubernetes cluster is a prerequisite here. Then the Kubernetes cluster will provide somehow similar features as Rancher Desktop. So, features of the foundation stack are the following 

- [ ] Documentation how to setup and prepare Rancher Desktop 
- [ ] Use `traefik` embedded to Rancher Desktop
- [ ] Use `cert-manager` for self-signed certs
- [ ] Do not use `external-dns` instead instruct how to user to maintain `/etc/hosts` file
- [ ] Use `istiod` 
- [ ] Use `dex` with local user auth for a start 

# Documentation

- [ ] Additional documentation on what is inside of the stack
- [ ] How to use 
- [ ] Implementation details
- [ ] anything else?
